### ISSUE TITLE
Translation of GVA 0x8903aff578 failed

### ISSUE THREAD

**Issue by fish3rman** [0vercl0k/wtf#41]
hi, first of all, thank you for providing such a cool fuzzer bro :)
but i got an error while trying hevd sample test files.

server
```
D:\wtf\targets\hevd>..\..\src\build\wtf.exe master --max_len=1028 --runs=10000000 --target .
Seeded with 8037290960217419384
Iterating through the corpus..
Sorting through the 1 entries..
Running server on tcp://localhost:31337..
#0 cov: 0 (+0) corp: 0 (0.0b) exec/s: -nan (1 nodes) lastcov: 6.0s crash: 0 timeout: 0 cr3: 0 uptime: 6.0s
Could not receive size (0)
Receive failed
```

client
```
D:\wtf\targets\hevd>..\..\src\build\wtf.exe fuzz --backend=bochscpu --name hevd --max_len 1028 --limit 10000000
Initializing the debugger instance.. (this takes a bit of time)
Setting debug register status to zero.
Setting debug register status to zero.
Dialing to tcp://localhost:31337/..
Translation of GVA 0x8903aff578 failed
```

and this is target dumps & wtf that i made based on README.md 
https://drive.google.com/file/d/1-18rDU_TY8uLHYimMhXO9169iFUVB6o8/view?usp=sharing

thanx...

**Comment by 0vercl0k** [comment]
Hey man, thanks for the detailed report I am able to reproduce! What a weird one...

I'll let you know when I know more about the issue!

Cheers

**Comment by 0vercl0k** [comment]
OK I think the issue is that your `@cr3` is not page aligned:
```
2: kd> r @cr3
cr3=000000003dfb4002
```

Please give #42 a try and let me know if this fixes your issue!

Cheers

**Comment by fish3rman** [comment]
thanks! but now i got an error while trying .\fuzz-bochscpu.bat command :(
error code is ```Security check failure or stack buffer overrun - code c0000409```

```
************* Path validation summary **************
Response                         Time (ms)     Location
Deferred                                       srv*C:\Symbols*https://msdl.microsoft.com/download/symbols
Symbol search path is: srv*C:\Symbols*https://msdl.microsoft.com/download/symbols
Executable search path is: 
ModLoad: 00007ff6`50d70000 00007ff6`52a22000   D:\wtf\src\build\wtf.exe
ModLoad: 00007ffb`1a730000 00007ffb`1a925000   C:\WINDOWS\SYSTEM32\ntdll.dll
ModLoad: 00007ffb`18dd0000 00007ffb`18e8e000   C:\WINDOWS\System32\KERNEL32.DLL
ModLoad: 00007ffb`18120000 00007ffb`183e9000   C:\WINDOWS\System32\KERNELBASE.dll
ModLoad: 00007ffb`19520000 00007ffb`1958b000   C:\WINDOWS\System32\WS2_32.dll
ModLoad: 00007ffb`19110000 00007ffb`1923a000   C:\WINDOWS\System32\RPCRT4.dll
ModLoad: 00007ffb`18f60000 00007ffb`1900c000   C:\WINDOWS\System32\ADVAPI32.dll
ModLoad: 00007ffb`19480000 00007ffb`1951e000   C:\WINDOWS\System32\msvcrt.dll
ModLoad: 00007ffb`19070000 00007ffb`1910b000   C:\WINDOWS\System32\sechost.dll
ModLoad: 00007ffa`fde80000 00007ffa`fdea6000   C:\WINDOWS\SYSTEM32\WinHvPlatform.dll
ModLoad: 00007ffb`17e80000 00007ffb`17f80000   C:\WINDOWS\System32\ucrtbase.dll
ModLoad: 00007ffb`18590000 00007ffb`18613000   C:\WINDOWS\System32\bcryptprimitives.dll
ModLoad: 00007ffb`04d40000 00007ffb`04dcd000   C:\WINDOWS\SYSTEM32\MSVCP140.dll
ModLoad: 00007ffb`09ac0000 00007ffb`09adb000   C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll
ModLoad: 00007ffb`0aec0000 00007ffb`0aecc000   C:\WINDOWS\SYSTEM32\VCRUNTIME140_1.dll
ModLoad: 00007ffb`17d50000 00007ffb`17d7e000   C:\WINDOWS\SYSTEM32\USERENV.dll
ModLoad: 00007ffb`11c20000 00007ffb`11c3b000   C:\WINDOWS\SYSTEM32\vid.dll
ModLoad: 00007ffb`17730000 00007ffb`1773c000   C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
ModLoad: 00007ffa`a8270000 00007ffa`a8a2d000   D:\wtf\src\build\dbgeng.dll
ModLoad: 00007ffb`18500000 00007ffb`18527000   C:\WINDOWS\System32\bcrypt.dll
ModLoad: 00007ffb`18e90000 00007ffb`18f5d000   C:\WINDOWS\System32\OLEAUT32.dll
ModLoad: 00007ffb`18030000 00007ffb`180cd000   C:\WINDOWS\System32\msvcp_win.dll
ModLoad: 00007ffb`18780000 00007ffb`18ad5000   C:\WINDOWS\System32\combase.dll
ModLoad: 00007ffa`f4330000 00007ffa`f43e4000   C:\WINDOWS\SYSTEM32\dbgmodel.dll
ModLoad: 00007ffb`13470000 00007ffb`134a6000   C:\WINDOWS\SYSTEM32\XmlLite.dll
ModLoad: 00007ffa`b7150000 00007ffa`b7333000   D:\wtf\src\build\dbghelp.dll
ModLoad: 00007ffb`00a80000 00007ffb`00a8c000   C:\WINDOWS\SYSTEM32\Secur32.dll
ModLoad: 00007ffb`17d10000 00007ffb`17d41000   C:\WINDOWS\SYSTEM32\SSPICLI.DLL
ModLoad: 00007ffb`1a5c0000 00007ffb`1a615000   C:\WINDOWS\System32\shlwapi.dll
ModLoad: 00007ffb`10eb0000 00007ffb`10eba000   C:\WINDOWS\SYSTEM32\version.dll
ModLoad: 00007ffb`19590000 00007ffb`196ba000   C:\WINDOWS\System32\ole32.dll
ModLoad: 00007ffb`19f80000 00007ffb`19fab000   C:\WINDOWS\System32\GDI32.dll
ModLoad: 00007ffb`17e50000 00007ffb`17e72000   C:\WINDOWS\System32\win32u.dll
ModLoad: 00007ffb`183f0000 00007ffb`184fb000   C:\WINDOWS\System32\gdi32full.dll
ModLoad: 00007ffb`19240000 00007ffb`193e1000   C:\WINDOWS\System32\USER32.dll
ModLoad: 00007ffb`19f20000 00007ffb`19f50000   C:\WINDOWS\System32\IMM32.DLL
ModLoad: 00007ffb`19fb0000 00007ffb`1a05d000   C:\WINDOWS\System32\shcore.dll
ModLoad: 00007ffa`c88c0000 00007ffa`c8934000   D:\wtf\src\build\symsrv.dll
ModLoad: 00007ffb`18620000 00007ffb`18776000   C:\WINDOWS\System32\CRYPT32.dll
(422c.2d34): Security check failure or stack buffer overrun - code c0000409 (!!! second chance !!!)
Subcode: 0x7 FAST_FAIL_FATAL_APP_EXIT 
ucrtbase!abort+0x4e:
00007ffb`17ef286e cd29            int     29h
0:000> r
rax=0000000000000001 rbx=000000471111c470 rcx=0000000000000007
rdx=000000000000000f rsi=00007ff651088de4 rdi=000000471111bcb0
rip=00007ffb17ef286e rsp=000000471111ba90 rbp=000000471111fbc0
 r8=0000000000000001  r9=000000471111ba38 r10=0000000000000012
r11=000001c739c693a2 r12=ffffffffffffffff r13=00007ffb183ae828
r14=0000000000000001 r15=000000471111bcb0
iopl=0         nv up ei pl nz na pe nc
cs=0033  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00000200
ucrtbase!abort+0x4e:
00007ffb`17ef286e cd29            int     29h
0:000> kb
 # RetAddr               : Args to Child                                                           : Call Site
00 00007ffb`17ef1f9f     : 00000047`00000003 00000000`00000003 00000020`00001000 00000000`01000000 : ucrtbase!abort+0x4e
01 00007ff6`51088e3e     : 00000000`01cb2000 00000000`0185c000 00000000`00000000 00000000`ffffffff : ucrtbase!terminate+0x1f
02 00007ffb`1822c347     : 00000000`00000000 00007ff6`51088de4 00000000`00000000 00007ffb`181698bb : wtf!__scrt_unhandled_exception_filter+0x5a [d:\a01\_work\6\s\src\vctools\crt\vcstartup\src\utility\utility_desktop.cpp @ 93] 
03 00007ffb`1a7d51b0     : 00000047`1111bd60 00007ffb`1a87663c 00000000`00000000 00000047`1111bcf8 : KERNELBASE!UnhandledExceptionFilter+0x1e7
04 00007ffb`1a7bc766     : 00007ffb`1a8a2a24 00007ffb`1a730000 00000047`1111bd60 00007ffb`1a760e7b : ntdll!RtlUserThreadStart$filt$0+0xa2
05 00007ffb`1a7d20cf     : 00000000`00000000 00000047`1111c260 00000047`1111ccc0 00000000`00000000 : ntdll!_C_specific_handler+0x96
06 00007ffb`1a781454     : 00000000`00000000 00000047`1111c260 00000047`1111ccc0 00000000`00000001 : ntdll!RtlpExecuteHandlerForException+0xf
07 00007ffb`1a7811a5     : 00000000`00000000 00000047`1111cb60 00000000`00000000 00000047`1111c470 : ntdll!RtlDispatchException+0x244
08 00007ffb`18154f99     : 00000002`fffffffe 00007ff6`5118a160 00000047`1111ce20 00007ff6`50f405e5 : ntdll!RtlRaiseException+0x185
09 00007ffb`09ac6480     : 00000047`1111ce20 00000000`00000000 00000000`00000000 00000000`00000000 : KERNELBASE!RaiseException+0x69
0a 00007ff6`50e59bc8     : 00007ff6`51130160 00000000`00000000 00007ff6`51130160 00000000`00000000 : VCRUNTIME140!_CxxThrowException+0x90 [d:\a01\_work\4\s\src\vctools\crt\vcruntime\src\eh\throw.cpp @ 75] 
0b (Inline Function)     : --------`-------- --------`-------- --------`-------- --------`-------- : wtf!fmt::v7::detail::do_throw+0x2a [D:\wtf\wtf-main\src\libs\fmt\include\fmt\format.h @ 107] 
0c (Inline Function)     : --------`-------- --------`-------- --------`-------- --------`-------- : wtf!fmt::v7::detail::error_handler::on_error+0x5d [D:\wtf\wtf-main\src\libs\fmt\include\fmt\format-inl.h @ 2737] 
0d (Inline Function)     : --------`-------- --------`-------- --------`-------- --------`-------- : wtf!fmt::v7::basic_format_context<fmt::v7::detail::buffer_appender<char>,char>::on_error+0x5d [D:\wtf\wtf-main\src\libs\fmt\include\fmt\core.h @ 1523] 
0e (Inline Function)     : --------`-------- --------`-------- --------`-------- --------`-------- : wtf!fmt::v7::detail::get_arg+0x215 [D:\wtf\wtf-main\src\libs\fmt\include\fmt\format.h @ 2569] 
0f 00007ff6`50e5a3e9     : 00000000`00000000 00000047`1111d200 00000000`00000000 fffff804`1c563000 : wtf!fmt::v7::detail::format_handler<fmt::v7::detail::buffer_appender<char>,char,fmt::v7::basic_format_context<fmt::v7::detail::buffer_appender<char>,char> >::on_format_specs+0x248 [D:\wtf\wtf-main\src\libs\fmt\include\fmt\format.h @ 3092] 
10 (Inline Function)     : --------`-------- --------`-------- --------`-------- --------`-------- : wtf!fmt::v7::detail::parse_replacement_field+0x8e [D:\wtf\wtf-main\src\libs\fmt\include\fmt\format.h @ 2983] 
11 00007ff6`50e5a694     : 00000000`00000000 00000000`00000000 00000047`1111d118 00000000`00000000 : wtf!fmt::v7::detail::parse_format_string<0,char,fmt::v7::detail::format_handler<fmt::v7::detail::buffer_appender<char>,char,fmt::v7::basic_format_context<fmt::v7::detail::buffer_appender<char>,char> > &>+0x429 [D:\wtf\wtf-main\src\libs\fmt\include\fmt\format.h @ 3039] 
12 00007ff6`50e38459     : 00000000`00000000 00000000`00000000 00000000`00000000 00000047`1111f244 : wtf!fmt::v7::detail::vformat_to<char>+0xd4 [D:\wtf\wtf-main\src\libs\fmt\include\fmt\format.h @ 3785] 
13 00007ff6`50ea4f5d     : fffff804`19812e40 00000000`00004700 00000000`00000002 00000000`431e7000 : wtf!fmt::v7::vprint+0x79 [D:\wtf\wtf-main\src\libs\fmt\include\fmt\format-inl.h @ 2769] 
14 (Inline Function)     : --------`-------- --------`-------- --------`-------- --------`-------- : wtf!fmt::v7::vprint+0x3b [D:\wtf\wtf-main\src\libs\fmt\include\fmt\format-inl.h @ 2796] 
15 (Inline Function)     : --------`-------- --------`-------- --------`-------- --------`-------- : wtf!fmt::v7::print+0x4c [D:\wtf\wtf-main\src\libs\fmt\include\fmt\core.h @ 2115] 
16 00007ff6`50ebb169     : 00007ff6`529e96f8 00007ff6`529e96f8 000001c7`39c752e0 000001c7`39c5afb8 : wtf!SanitizeCpuState+0x27d [D:\wtf\wtf-main\src\wtf\utils.cc @ 225] 
17 00007ff6`5108828c     : 00000000`00000000 00000000`00000000 000001c7`39c5b3e0 00000000`00000000 : wtf!main+0x1cb9 [D:\wtf\wtf-main\src\wtf\wtf.cc @ 398] 
18 (Inline Function)     : --------`-------- --------`-------- --------`-------- --------`-------- : wtf!invoke_main+0x22 [d:\a01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 78] 
19 00007ffb`18de7034     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : wtf!__scrt_common_main_seh+0x10c [d:\a01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 288] 
1a 00007ffb`1a782651     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : KERNEL32!BaseThreadInitThunk+0x14
1b 00000000`00000000     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!RtlUserThreadStart+0x21
```

**Comment by 0vercl0k** [comment]
Ugh sorry I messed up my fix - it should be working now 😇

Cheers

**Comment by fish3rman** [comment]
unfortunately crash occured again :(
i dont know what's wrong with this...
i did 
1. src/build/build-release.bat with x64 Native Tools Command Prompt for VS 2019
2. open terminal and launch server.bat
3. open another terminal and launch fuzz-bochscpu.bat

sorry for bothering you 

server
```D:\wtf\wtf-fbl_cr3\targets\hevd>..\..\src\build\wtf.exe master --max_len=1028 --runs=10000000 --target .
Seeded with 1884932881438055736
Iterating through the corpus..
Sorting through the 1 entries..
Running server on tcp://localhost:31337..
#0 cov: 0 (+0) corp: 0 (0.0b) exec/s: 0.0 (0 nodes) lastcov: 30.0s crash: 0 timeout: 0 cr3: 0 uptime: 30.0s
#0 cov: 0 (+0) corp: 0 (0.0b) exec/s: -nan (1 nodes) lastcov: 30.0s crash: 0 timeout: 0 cr3: 0 uptime: 30.0s
```

client
```D:\wtf\wtf-fbl_cr3\targets\hevd>..\..\src\build\wtf.exe fuzz --backend=bochscpu --name hevd --max_len 1028 --limit 10000000
Initializing the debugger instance.. (this takes a bit of time)
Setting debug register status to zero.
Setting debug register status to zero.
The @cr3 (431e7002) register is not aligned.. aligning it.
Dialing to tcp://localhost:31337/..
Translation of GVA 0x8903aff578 failed
Failed to insert testcase
```

crash

```************* Path validation summary **************
Response                         Time (ms)     Location
Deferred                                       srv*C:\Symbols*https://msdl.microsoft.com/download/symbols
Symbol search path is: srv*C:\Symbols*https://msdl.microsoft.com/download/symbols
Executable search path is: 
ModLoad: 00007ff7`53bf0000 00007ff7`5588c000   D:\wtf\wtf-fbl_cr3\src\build\wtf.exe
ModLoad: 00007ffb`1a730000 00007ffb`1a925000   C:\WINDOWS\SYSTEM32\ntdll.dll
ModLoad: 00007ffb`18dd0000 00007ffb`18e8e000   C:\WINDOWS\System32\KERNEL32.DLL
ModLoad: 00007ffb`18120000 00007ffb`183e9000   C:\WINDOWS\System32\KERNELBASE.dll
ModLoad: 00007ffb`19520000 00007ffb`1958b000   C:\WINDOWS\System32\WS2_32.dll
ModLoad: 00007ffb`19110000 00007ffb`1923a000   C:\WINDOWS\System32\RPCRT4.dll
ModLoad: 00007ffb`18f60000 00007ffb`1900c000   C:\WINDOWS\System32\ADVAPI32.dll
ModLoad: 00007ffb`19480000 00007ffb`1951e000   C:\WINDOWS\System32\msvcrt.dll
ModLoad: 00007ffb`19070000 00007ffb`1910b000   C:\WINDOWS\System32\sechost.dll
ModLoad: 00007ffa`f96e0000 00007ffa`f9706000   C:\WINDOWS\SYSTEM32\WinHvPlatform.dll
ModLoad: 00007ffb`17e80000 00007ffb`17f80000   C:\WINDOWS\System32\ucrtbase.dll
ModLoad: 00007ffb`18590000 00007ffb`18613000   C:\WINDOWS\System32\bcryptprimitives.dll
ModLoad: 00007ffb`04d40000 00007ffb`04dcd000   C:\WINDOWS\SYSTEM32\MSVCP140.dll
ModLoad: 00007ffb`0aec0000 00007ffb`0aecc000   C:\WINDOWS\SYSTEM32\VCRUNTIME140_1.dll
ModLoad: 00007ffb`09ac0000 00007ffb`09adb000   C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll
ModLoad: 00007ffb`17d50000 00007ffb`17d7e000   C:\WINDOWS\SYSTEM32\USERENV.dll
ModLoad: 00007ffb`11c20000 00007ffb`11c3b000   C:\WINDOWS\SYSTEM32\vid.dll
ModLoad: 00007ffb`17730000 00007ffb`1773c000   C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
ModLoad: 00007ffa`a8270000 00007ffa`a8a2d000   D:\wtf\wtf-fbl_cr3\src\build\dbgeng.dll
ModLoad: 00007ffb`18500000 00007ffb`18527000   C:\WINDOWS\System32\bcrypt.dll
ModLoad: 00007ffb`18e90000 00007ffb`18f5d000   C:\WINDOWS\System32\OLEAUT32.dll
ModLoad: 00007ffb`18030000 00007ffb`180cd000   C:\WINDOWS\System32\msvcp_win.dll
ModLoad: 00007ffa`e8c50000 00007ffa`e8d04000   C:\WINDOWS\SYSTEM32\dbgmodel.dll
ModLoad: 00007ffb`18780000 00007ffb`18ad5000   C:\WINDOWS\System32\combase.dll
ModLoad: 00007ffa`dd790000 00007ffa`dd973000   D:\wtf\wtf-fbl_cr3\src\build\dbghelp.dll
ModLoad: 00007ffb`13470000 00007ffb`134a6000   C:\WINDOWS\SYSTEM32\XmlLite.dll
ModLoad: 00007ffb`00a80000 00007ffb`00a8c000   C:\WINDOWS\SYSTEM32\Secur32.dll
ModLoad: 00007ffb`17d10000 00007ffb`17d41000   C:\WINDOWS\SYSTEM32\SSPICLI.DLL
ModLoad: 00007ffb`1a5c0000 00007ffb`1a615000   C:\WINDOWS\System32\shlwapi.dll
ModLoad: 00007ffb`10eb0000 00007ffb`10eba000   C:\WINDOWS\SYSTEM32\version.dll
ModLoad: 00007ffb`19590000 00007ffb`196ba000   C:\WINDOWS\System32\ole32.dll
ModLoad: 00007ffb`19f80000 00007ffb`19fab000   C:\WINDOWS\System32\GDI32.dll
ModLoad: 00007ffb`17e50000 00007ffb`17e72000   C:\WINDOWS\System32\win32u.dll
ModLoad: 00007ffb`183f0000 00007ffb`184fb000   C:\WINDOWS\System32\gdi32full.dll
ModLoad: 00007ffb`19240000 00007ffb`193e1000   C:\WINDOWS\System32\USER32.dll
ModLoad: 00007ffb`19f20000 00007ffb`19f50000   C:\WINDOWS\System32\IMM32.DLL
ModLoad: 00007ffb`19fb0000 00007ffb`1a05d000   C:\WINDOWS\System32\shcore.dll
ModLoad: 00007ffa`e9280000 00007ffa`e92f4000   D:\wtf\wtf-fbl_cr3\src\build\symsrv.dll
ModLoad: 00007ffb`18620000 00007ffb`18776000   C:\WINDOWS\System32\CRYPT32.dll
ModLoad: 00007ffb`175a0000 00007ffb`1760a000   C:\WINDOWS\System32\mswsock.dll
ModLoad: 00007ffb`172a0000 00007ffb`1736c000   C:\WINDOWS\SYSTEM32\DNSAPI.dll
ModLoad: 00007ffb`17260000 00007ffb`1729b000   C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
ModLoad: 00007ffb`1a680000 00007ffb`1a688000   C:\WINDOWS\System32\NSI.dll
ModLoad: 00000000`6f9f0000 00000000`6fa16000   C:\Program Files\Bonjour\mdnsNSP.dll
ModLoad: 00007ffb`10d20000 00007ffb`10d9f000   C:\WINDOWS\System32\fwpuclnt.dll
ModLoad: 00007ffb`0e390000 00007ffb`0e39a000   C:\Windows\System32\rasadhlp.dll
(4d10.7b20): Break instruction exception - code 80000003 (!!! second chance !!!)
*** WARNING: Unable to verify checksum for D:\wtf\wtf-fbl_cr3\src\build\wtf.exe
wtf!Backend_t::VirtWrite+0x128:
00007ff7`53c8e0c8 cc              int     3
0:000> g
(4d10.7b20): Security check failure or stack buffer overrun - code c0000409 (!!! second chance !!!)
Subcode: 0x7 FAST_FAIL_FATAL_APP_EXIT 
ucrtbase!abort+0x4e:
00007ffb`17ef286e cd29            int     29h
0:000> kb 
 # RetAddr               : Args to Child                                                           : Call Site
00 00007ff7`53ce7fc9     : 000000a1`00000003 00000000`00000003 000000a1`98afd6d0 0100007f`697a0002 : ucrtbase!abort+0x4e
01 00007ff7`53ce87e3     : 000000a1`98afd680 000000a1`98afd740 000000a1`98afd6b9 000000a1`98afd740 : wtf!RunTestcaseAndRestore+0x49 [D:\wtf\wtf-fbl_cr3\src\wtf\client.cc @ 104] 
02 00007ff7`53d06a5c     : 000000a1`98afd740 00000000`00000000 000000a1`98afefb0 000000a1`98afefb0 : wtf!Client_t::Run+0x223 [D:\wtf\wtf-fbl_cr3\src\wtf\client.cc @ 233] 
03 00007ff7`53d2ca96     : 00007ff7`558536d0 00007ff7`558536d0 00007ff7`558536d0 00000290`3e184e88 : wtf!FuzzSubcommand+0x2c [D:\wtf\wtf-fbl_cr3\src\wtf\subcommands.cc @ 96] 
04 00007ff7`53ef58fc     : 00000000`00000000 00000000`00000000 00000290`3e1891e0 00000000`00000000 : wtf!main+0x1f46 [D:\wtf\wtf-fbl_cr3\src\wtf\wtf.cc @ 419] 
05 (Inline Function)     : --------`-------- --------`-------- --------`-------- --------`-------- : wtf!invoke_main+0x22 [d:\a01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 78] 
06 00007ffb`18de7034     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : wtf!__scrt_common_main_seh+0x10c [d:\a01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 288] 
07 00007ffb`1a782651     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : KERNEL32!BaseThreadInitThunk+0x14
08 00000000`00000000     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!RtlUserThreadStart+0x21```

**Comment by 0vercl0k** [comment]
Hmm, let me have another look.. Sorry for the back and forth 🤦🏽‍♂️

**Comment by 0vercl0k** [comment]
OK so I think I went off the wrong direction - in your `regs.json` the `@cr3` value is: `0x431e7002` but if you load the dump in windbg this is what it tells you:
```
2: kd> r @cr3
cr3=000000003dfb4002
```

After doing a bit of reading, the lower bits in the `@cr3` are actually the PCID (used for TLBs) and so doesn't need to be "page-aligned".

Can you simply open your `regs.json` and set the `cr3` value to `0x3dfb4002` and give it a go?

Cheers

**Comment by dr0gba** [comment]
now "Translation of GVA 0x8903aff578 failed" message didnt pop up but still crashed

bochscpu
```D:\wtf\wtf-fbl_cr3\targets\hevd>..\..\src\build\wtf.exe fuzz --backend=bochscpu --name hevd --max_len 1028 --limit 10000000
Initializing the debugger instance.. (this takes a bit of time)
Setting debug register status to zero.
Setting debug register status to zero.
The @cr3 (3dfb4002) register is not aligned.. aligning it.
Dialing to tcp://localhost:31337/..
```

whv
```
D:\wtf\wtf-fbl_cr3\targets\hevd>..\..\src\build\wtf.exe fuzz --backend=whv --name hevd --max_len 1028 --limit 3
Initializing the debugger instance.. (this takes a bit of time)
Parsing coverage\HEVD.cov..
Applied 432 code coverage breakpoints
Setting debug register status to zero.
Setting debug register status to zero.
The @cr3 (3dfb4002) register is not aligned.. aligning it.
Resolved breakpoint 0x7ff69e951124 at GPA 0x501ee124 aka HVA 0x1f6824a0124
Resolved breakpoint 0xfffff8041917d1d0 at GPA 0x4b7d1d0 aka HVA 0x1f6824ab1d0
Resolved breakpoint 0xfffff80419050724 at GPA 0x4a50724 aka HVA 0x1f68249e724
Resolved breakpoint 0xfffff804193117b0 at GPA 0x4d117b0 aka HVA 0x1f6824af7b0
Resolved breakpoint 0xfffff804191fe210 at GPA 0x4bfe210 aka HVA 0x1f6824b3210
Dialing to tcp://localhost:31337/..
Could not receive size (-1)
Receive failed
#1 cov: 0 exec/s: 0.1 lastcov: 18.0s crash: 0 timeout: 0 cr3: 1 uptime: 18.0s
```

```************* Path validation summary **************
Response                         Time (ms)     Location
Deferred                                       srv*C:\Symbols*https://msdl.microsoft.com/download/symbols
Symbol search path is: srv*C:\Symbols*https://msdl.microsoft.com/download/symbols
Executable search path is: 
ModLoad: 00007ff7`53bf0000 00007ff7`5588c000   D:\wtf\wtf-fbl_cr3\src\build\wtf.exe
ModLoad: 00007ffb`1a730000 00007ffb`1a925000   C:\WINDOWS\SYSTEM32\ntdll.dll
ModLoad: 00007ffb`18dd0000 00007ffb`18e8e000   C:\WINDOWS\System32\KERNEL32.DLL
ModLoad: 00007ffb`18120000 00007ffb`183e9000   C:\WINDOWS\System32\KERNELBASE.dll
ModLoad: 00007ffb`19520000 00007ffb`1958b000   C:\WINDOWS\System32\WS2_32.dll
ModLoad: 00007ffb`19110000 00007ffb`1923a000   C:\WINDOWS\System32\RPCRT4.dll
ModLoad: 00007ffb`18f60000 00007ffb`1900c000   C:\WINDOWS\System32\ADVAPI32.dll
ModLoad: 00007ffb`19480000 00007ffb`1951e000   C:\WINDOWS\System32\msvcrt.dll
ModLoad: 00007ffb`19070000 00007ffb`1910b000   C:\WINDOWS\System32\sechost.dll
ModLoad: 00007ffb`17e80000 00007ffb`17f80000   C:\WINDOWS\System32\ucrtbase.dll
ModLoad: 00007ffa`fde80000 00007ffa`fdea6000   C:\WINDOWS\SYSTEM32\WinHvPlatform.dll
ModLoad: 00007ffb`18590000 00007ffb`18613000   C:\WINDOWS\System32\bcryptprimitives.dll
ModLoad: 00007ffb`04d40000 00007ffb`04dcd000   C:\WINDOWS\SYSTEM32\MSVCP140.dll
ModLoad: 00007ffb`0aec0000 00007ffb`0aecc000   C:\WINDOWS\SYSTEM32\VCRUNTIME140_1.dll
ModLoad: 00007ffb`09ac0000 00007ffb`09adb000   C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll
ModLoad: 00007ffb`17d50000 00007ffb`17d7e000   C:\WINDOWS\SYSTEM32\USERENV.dll
ModLoad: 00007ffb`11c20000 00007ffb`11c3b000   C:\WINDOWS\SYSTEM32\vid.dll
ModLoad: 00007ffb`17730000 00007ffb`1773c000   C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
ModLoad: 00007ffb`175a0000 00007ffb`1760a000   C:\WINDOWS\System32\mswsock.dll
ModLoad: 00007ffb`172a0000 00007ffb`1736c000   C:\WINDOWS\SYSTEM32\DNSAPI.dll
ModLoad: 00007ffb`17260000 00007ffb`1729b000   C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
ModLoad: 00007ffb`1a680000 00007ffb`1a688000   C:\WINDOWS\System32\NSI.dll
ModLoad: 00000000`6f9f0000 00000000`6fa16000   C:\Program Files\Bonjour\mdnsNSP.dll
ModLoad: 00007ffb`10d20000 00007ffb`10d9f000   C:\WINDOWS\System32\fwpuclnt.dll
ModLoad: 00007ffb`18500000 00007ffb`18527000   C:\WINDOWS\System32\bcrypt.dll
ModLoad: 00007ffb`0e390000 00007ffb`0e39a000   C:\Windows\System32\rasadhlp.dll
(7e30.63dc): Security check failure or stack buffer overrun - code c0000409 (!!! second chance !!!)
Subcode: 0x7 FAST_FAIL_FATAL_APP_EXIT 
*** WARNING: Unable to verify checksum for D:\wtf\wtf-fbl_cr3\src\build\wtf.exe
ucrtbase!abort+0x4e:
00007ffb`17ef286e cd29            int     29h
0:000> kb
 # RetAddr               : Args to Child                                                           : Call Site
00 00007ff7`53d051c3     : 00000000`00000003 00000000`00000003 0000000c`cdd5bc80 00007ffb`00000030 : ucrtbase!abort+0x4e
01 00007ff7`53d05382     : 0000000c`cdd5dac8 00007ff7`53d03979 00000176`e787ff50 00000000`00000004 : wtf!Server_t::GetTestcase+0x463 [D:\wtf\wtf-fbl_cr3\src\wtf\server.h @ 716] 
02 00007ff7`53d048ef     : 00000000`00000000 00000176`e787b470 00000176`e787ff50 00000000`0000018c : wtf!Server_t::HandleNewRequest+0x32 [D:\wtf\wtf-fbl_cr3\src\wtf\server.h @ 788] 
03 00007ff7`53d06ad4     : 0000000c`cdd5c270 00000176`e787c8c0 00000176`e7875380 00000176`e787abd0 : wtf!Server_t::Run+0xa1f [D:\wtf\wtf-fbl_cr3\src\wtf\server.h @ 579] 
04 00007ff7`53d2c85b     : 00000176`e787c8c0 00000176`e787c8c0 00000176`e7875380 00000176`e7875380 : wtf!MasterSubcommand+0x44 [D:\wtf\wtf-fbl_cr3\src\wtf\subcommands.cc @ 100] 
05 00007ff7`53ef58fc     : 00000000`00000000 00000000`00000000 00000176`e7853110 00000000`00000000 : wtf!main+0x1d0b [D:\wtf\wtf-fbl_cr3\src\wtf\wtf.cc @ 326] 
06 (Inline Function)     : --------`-------- --------`-------- --------`-------- --------`-------- : wtf!invoke_main+0x22 [d:\a01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 78] 
07 00007ffb`18de7034     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : wtf!__scrt_common_main_seh+0x10c [d:\a01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 288] 
08 00007ffb`1a782651     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : KERNEL32!BaseThreadInitThunk+0x14
09 00000000`00000000     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!RtlUserThreadStart+0x21
```

**Comment by fish3rman** [comment]
now "Translation of GVA 0x8903aff578 failed" message didnt pop up but still crashed

bochscpu
```D:\wtf\wtf-fbl_cr3\targets\hevd>..\..\src\build\wtf.exe fuzz --backend=bochscpu --name hevd --max_len 1028 --limit 10000000
Initializing the debugger instance.. (this takes a bit of time)
Setting debug register status to zero.
Setting debug register status to zero.
The @cr3 (3dfb4002) register is not aligned.. aligning it.
Dialing to tcp://localhost:31337/..
```

whv
```
D:\wtf\wtf-fbl_cr3\targets\hevd>..\..\src\build\wtf.exe fuzz --backend=whv --name hevd --max_len 1028 --limit 3
Initializing the debugger instance.. (this takes a bit of time)
Parsing coverage\HEVD.cov..
Applied 432 code coverage breakpoints
Setting debug register status to zero.
Setting debug register status to zero.
The @cr3 (3dfb4002) register is not aligned.. aligning it.
Resolved breakpoint 0x7ff69e951124 at GPA 0x501ee124 aka HVA 0x1f6824a0124
Resolved breakpoint 0xfffff8041917d1d0 at GPA 0x4b7d1d0 aka HVA 0x1f6824ab1d0
Resolved breakpoint 0xfffff80419050724 at GPA 0x4a50724 aka HVA 0x1f68249e724
Resolved breakpoint 0xfffff804193117b0 at GPA 0x4d117b0 aka HVA 0x1f6824af7b0
Resolved breakpoint 0xfffff804191fe210 at GPA 0x4bfe210 aka HVA 0x1f6824b3210
Dialing to tcp://localhost:31337/..
Could not receive size (-1)
Receive failed
#1 cov: 0 exec/s: 0.1 lastcov: 18.0s crash: 0 timeout: 0 cr3: 1 uptime: 18.0s
```

```************* Path validation summary **************
Response                         Time (ms)     Location
Deferred                                       srv*C:\Symbols*https://msdl.microsoft.com/download/symbols
Symbol search path is: srv*C:\Symbols*https://msdl.microsoft.com/download/symbols
Executable search path is: 
ModLoad: 00007ff7`53bf0000 00007ff7`5588c000   D:\wtf\wtf-fbl_cr3\src\build\wtf.exe
ModLoad: 00007ffb`1a730000 00007ffb`1a925000   C:\WINDOWS\SYSTEM32\ntdll.dll
ModLoad: 00007ffb`18dd0000 00007ffb`18e8e000   C:\WINDOWS\System32\KERNEL32.DLL
ModLoad: 00007ffb`18120000 00007ffb`183e9000   C:\WINDOWS\System32\KERNELBASE.dll
ModLoad: 00007ffb`19520000 00007ffb`1958b000   C:\WINDOWS\System32\WS2_32.dll
ModLoad: 00007ffb`19110000 00007ffb`1923a000   C:\WINDOWS\System32\RPCRT4.dll
ModLoad: 00007ffb`18f60000 00007ffb`1900c000   C:\WINDOWS\System32\ADVAPI32.dll
ModLoad: 00007ffb`19480000 00007ffb`1951e000   C:\WINDOWS\System32\msvcrt.dll
ModLoad: 00007ffb`19070000 00007ffb`1910b000   C:\WINDOWS\System32\sechost.dll
ModLoad: 00007ffb`17e80000 00007ffb`17f80000   C:\WINDOWS\System32\ucrtbase.dll
ModLoad: 00007ffa`fde80000 00007ffa`fdea6000   C:\WINDOWS\SYSTEM32\WinHvPlatform.dll
ModLoad: 00007ffb`18590000 00007ffb`18613000   C:\WINDOWS\System32\bcryptprimitives.dll
ModLoad: 00007ffb`04d40000 00007ffb`04dcd000   C:\WINDOWS\SYSTEM32\MSVCP140.dll
ModLoad: 00007ffb`0aec0000 00007ffb`0aecc000   C:\WINDOWS\SYSTEM32\VCRUNTIME140_1.dll
ModLoad: 00007ffb`09ac0000 00007ffb`09adb000   C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll
ModLoad: 00007ffb`17d50000 00007ffb`17d7e000   C:\WINDOWS\SYSTEM32\USERENV.dll
ModLoad: 00007ffb`11c20000 00007ffb`11c3b000   C:\WINDOWS\SYSTEM32\vid.dll
ModLoad: 00007ffb`17730000 00007ffb`1773c000   C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
ModLoad: 00007ffb`175a0000 00007ffb`1760a000   C:\WINDOWS\System32\mswsock.dll
ModLoad: 00007ffb`172a0000 00007ffb`1736c000   C:\WINDOWS\SYSTEM32\DNSAPI.dll
ModLoad: 00007ffb`17260000 00007ffb`1729b000   C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
ModLoad: 00007ffb`1a680000 00007ffb`1a688000   C:\WINDOWS\System32\NSI.dll
ModLoad: 00000000`6f9f0000 00000000`6fa16000   C:\Program Files\Bonjour\mdnsNSP.dll
ModLoad: 00007ffb`10d20000 00007ffb`10d9f000   C:\WINDOWS\System32\fwpuclnt.dll
ModLoad: 00007ffb`18500000 00007ffb`18527000   C:\WINDOWS\System32\bcrypt.dll
ModLoad: 00007ffb`0e390000 00007ffb`0e39a000   C:\Windows\System32\rasadhlp.dll
(7e30.63dc): Security check failure or stack buffer overrun - code c0000409 (!!! second chance !!!)
Subcode: 0x7 FAST_FAIL_FATAL_APP_EXIT 
*** WARNING: Unable to verify checksum for D:\wtf\wtf-fbl_cr3\src\build\wtf.exe
ucrtbase!abort+0x4e:
00007ffb`17ef286e cd29            int     29h
0:000> kb
 # RetAddr               : Args to Child                                                           : Call Site
00 00007ff7`53d051c3     : 00000000`00000003 00000000`00000003 0000000c`cdd5bc80 00007ffb`00000030 : ucrtbase!abort+0x4e
01 00007ff7`53d05382     : 0000000c`cdd5dac8 00007ff7`53d03979 00000176`e787ff50 00000000`00000004 : wtf!Server_t::GetTestcase+0x463 [D:\wtf\wtf-fbl_cr3\src\wtf\server.h @ 716] 
02 00007ff7`53d048ef     : 00000000`00000000 00000176`e787b470 00000176`e787ff50 00000000`0000018c : wtf!Server_t::HandleNewRequest+0x32 [D:\wtf\wtf-fbl_cr3\src\wtf\server.h @ 788] 
03 00007ff7`53d06ad4     : 0000000c`cdd5c270 00000176`e787c8c0 00000176`e7875380 00000176`e787abd0 : wtf!Server_t::Run+0xa1f [D:\wtf\wtf-fbl_cr3\src\wtf\server.h @ 579] 
04 00007ff7`53d2c85b     : 00000176`e787c8c0 00000176`e787c8c0 00000176`e7875380 00000176`e7875380 : wtf!MasterSubcommand+0x44 [D:\wtf\wtf-fbl_cr3\src\wtf\subcommands.cc @ 100] 
05 00007ff7`53ef58fc     : 00000000`00000000 00000000`00000000 00000176`e7853110 00000000`00000000 : wtf!main+0x1d0b [D:\wtf\wtf-fbl_cr3\src\wtf\wtf.cc @ 326] 
06 (Inline Function)     : --------`-------- --------`-------- --------`-------- --------`-------- : wtf!invoke_main+0x22 [d:\a01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 78] 
07 00007ffb`18de7034     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : wtf!__scrt_common_main_seh+0x10c [d:\a01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 288] 
08 00007ffb`1a782651     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : KERNEL32!BaseThreadInitThunk+0x14
09 00000000`00000000     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!RtlUserThreadStart+0x21
```

**Comment by 0vercl0k** [comment]
Ok cool - based on your stack-trace it maps to:
```C++
    const Testcase_t *Testcase = Corpus_.PickTestcase();
    if (!Testcase) {
      fmt::print("The corpus is empty, exiting\n");
      std::abort();
    }
```

Which means your `input` directory is empty or that any files that are in this directory didn't generate any new code-coverage; so all those testcases have been discarded :). Basically no HEVD code seems executed so I generated a `rip` trace of the test case to investigate and here's what we see:
```
KERNEL32!DeviceIoControlImplementation+0x70
KERNEL32!DeviceIoControlImplementation+0x75
KERNEL32!DeviceIoControlImplementation+0x7a
nt!KiPageFaultShadow+0x0
```

If we load the `mem.dmp` in Windbg we can see the below:
```
2: kd> u KERNEL32!DeviceIoControlImplementation+0x7a l1
KERNEL32!DeviceIoControlImplementation+0x7a:
00007fff`99bd560a 48ff152fce0600  call    qword ptr [KERNEL32!_imp_DeviceIoControl (00007fff`99c42440)]

2: kd> dqs 00007fff`99c42440 l1
00007fff`99c42440  00007fff`97e9b010 KERNELBASE!DeviceIoControl

2: kd> u KERNELBASE!DeviceIoControl l1
KERNELBASE!DeviceIoControl:
00007fff`97e9b010 ??              ???
```

Your dump basically has part of `kernelbase`'s code being swapped out which means `wtf` cannot execute the code :) And the fault is taken before even executing any HEVD code which explains the `cov: 0` in output above!

To avoid those issues I've developed https://github.com/0vercl0k/lockmem to lock every memory pages inside the process's working set.

Also just out of curiosity, what's the configuration of your VM (ram, etc.)?

Cheers

**Comment by wumb0** [comment]
May want to turn off [Kernel Virtual Address Shadow](https://wumb0.in/windows-10-kvas-and-software-smep.html) before using this fuzzer. CR3 is "not aligned" because the bottom few bits contain flags that indicate which set of page tables are being used. It may or may not affect your fuzzing. Try turning KVAS **off** via the disable-kva.cmd script in the scripts folder of the repo.

**Comment by fish3rman** [comment]
hi sorry for late reply
disable-kva.cmd didnt work
and I do not know which process lockmem is applied to in the virtual machine.

my WHV configuration is Windows 10 x64 20H2, 4gb of ram and 4 processors 
thanks

**Comment by wumb0** [comment]
Try reducing to one processor.

**Comment by fish3rman** [comment]
holy shit the problem was the processor ...
thanx dude

**Comment by fish3rman** [comment]
holy shit the problem was the processor ...
thanx dude

**Comment by wumb0** [comment]
😀
happy hacking
